version: '2'

services:
  postgres:
    image: postgres:14
    container_name: kurkuma-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kurkuma
    ports:
      - "5432:5432"